name = "MooreJuliaMultigrid"
uuid = "829f33e0-e95e-11e9-10c1-a950df6d3d72"
authors = ["Nicholas Moore"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
